import { writable } from "svelte/store";

export let menuItems = writable([
  {
    title: "Basmati Khazana",
    smallItems: [
      {
        name: "Veg. Biryani",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 190,
        oldprize: 190,
      },
      {
        name: "Veg. Hyderabadi Biryani",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 220,
        oldprize: 220,
      },
      {
        name: "Veg. Handi Biryani",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 180,
        oldprize: 180,
      },
      {
        name: "Cheese Biryani",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 200,
        oldprize: 200,
      },
      {
        name: "Paneer Biryani",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 220,
        oldprize: 220,
      },
      {
        name: "Chicken Dum Biryani",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 260,
        oldprize: 260,
      },
      {
        name: "Kolkata Chicken Biryani",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 320,
        oldprize: 320,
      },
      {
        name: "Egg Biryani",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 220,
        oldprize: 220,
      },
    ],
  },
  {
    title: "Pav Bhaji",
    smallItems: [
      {
        name: "Pav Bhaji",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 110,
        oldprize: 110,
      },
      {
        name: "Jain Pav Bhaji",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 90,
        oldprize: 90,
      },
      {
        name: "Cheese Pav Bhaji",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 120,
        oldprize: 120,
      },
      {
        name: "Toast Pav Bhaji",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 130,
        oldprize: 130,
      },
      {
        name: "Butter Pav (Single)",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 10,
        oldprize: 10,
      },
      {
        name: "Plain Pav (2 Pc)",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 5,
        oldprize: 5,
      },
    ],
  },
  {
    title: "Main Course",
    smallItems: [
      {
        name: "Veg Peshwari",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 220,
        oldprize: 220,
      },
      {
        name: "Paneer Butter Masala",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 200,
        oldprize: 200,
      },
      {
        name: "Veg. Pattiyala",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 200,
        oldprize: 200,
      },
      {
        name: "Panner Makkanwala",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 180,
        oldprize: 180,
      },
      {
        name: " Dum Aloo Kashmiri",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 200,
        oldprize: 200,
      },
      {
        name: "Paneer Kolhapuri",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 210,
        oldprize: 210,
      },
    ],
  },
  {
    title: "Chinese Cuisine",
    smallItems: [
      {
        name: "Veg. Fried Rice",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 120,
        oldprize: 120,
      },
      {
        name: "Veg. Schezwan Fried Rice",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 140,
        oldprize: 140,
      },
      {
        name: "Triple Schezwan Rice",
        qnt: 0,
        veg: true,
        visible: false,
        prize: 210,
        oldprize: 210,
      },
      {
        name: "Chicken Schezwan Rice",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 150,
        oldprize: 150,
      },
      {
        name: "Chicken Triple Rice",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 220,
        oldprize: 220,
      },
      {
        name: "Chicken Manchurian Rice",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 190,
        oldprize: 190,
      },
      {
        name: "Egg Schezwan Rice",
        qnt: 0,
        veg: false,
        visible: false,
        prize: 120,
        oldprize: 120,
      },
    ],
  },
]);

export let availNum = writable(2);
